[env]
TERM = "alacritty"

[font]
size = 9.0

[font.bold]
family = "Fira Code"
style = "Bold"

[font.bold_italic]
family = "Fira Code"
style = "Bold Italic"

[font.italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"
style = "Retina"

[selection]
save_to_clipboard = false

[window]
decorations = "full"
decorations_theme_variant = "None"
dynamic_title = true
startup_mode = "Windowed"

[window.dimensions]
columns = 120
lines = 47
