[env]
TERM = "alacritty"

[font]
size = 13.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
# family = "FiraCode Nerd Font Mono"
style = "Retina"

[selection]
save_to_clipboard = false

[window]
decorations = "full"
decorations_theme_variant = "None"
dynamic_title = true
startup_mode = "Windowed"

[window.dimensions]
columns = 120
lines = 47

# [keyboard]
# bindings = [
#   { key= "Left",  mods= "Alt", chars= "\eb" },
#   # { key= "Left",  mods= "Alt", chars= "\x1BB" },
#   # { key= "Right", mods= "Alt", chars= "\x1BF" },
# ]

# - { key: Right, mods: Alt, chars: "\x1BF" }
# - { key: Left,  mods: Alt, chars: "\x1BB" }
