if [ -f ~/.profile ]; then
	. ~/.profile
fi

# Package wrapper.
alias update-system="yaourt -Syua"
alias clean-pacman-cache="sudo pacman -Sc ; sudo paccache -rk1"
alias tmux='tmux -2'
alias e="exa -lg"
alias ea="exa -lag"
alias vcp='rsync --info=progress2 -Wh -a'
alias vcpdry='rsync --progress -Whn -a'

# Rust aliases
#alias cargo="RUSTFLAGS='-C target-cpu=native' CARGO_INCREMENTAL=1 TERM=xterm-color cargo"
alias cargo="CARGO_INCREMENTAL=1 TERM=xterm-color cargo"
alias update-rust="bash ~/junk/repo/bearded-happiness/rust/rust_update.sh"
alias reset_rust="rm -rf ~/.cargo/* ~/.rustup/* ~/.multirust/* ; ~/junk/repo/bearded-happiness/rust/rust_install.sh ; update-neovim"

# NeoVim part
alias nv="nvim"
alias neovimconfig="nvim ~/.config/nvim/init.vim"
alias update-neovim="nvim +PlugClean +qa && nvim +PlugInstall +UpdateRemotePlugins +qa && nvim +PlugUpdate +UpdateRemotePlugins +qa"
alias reset-neovim='rm -rf ~/.config/nvim/plugged && update-neovim && sed -ie "s\\hi! link Operator Normal\\hi! link Operator GruvboxBlueBold\\g" ~/.config/nvim/plugged/gruvbox/colors/gruvbox.vim'
alias update-vim="vim +PlugClean +qall && vim +PlugInstall +UpdateRemotePlugins +qall && vim +PlugUpdate +UpdateRemotePlugins +qall"

# Git aliases
alias gdf="git diff"

